services:
  K3Progetti\SoftwareVersionBundle\:
    resource: '../../src/'
    exclude:
      - '../../src/DependencyInjection/'
      - '../../src/Entity/'
      - '../../src/Tests/'
      - '../../src/Event/'
    autowire: true
    autoconfigure: true
    public: true
